- title: "SoNIC: Safe Social Navigation with Adaptive Conformal Inference and Constrained Reinforcement Learning"
  authors:
    - J. Yao
    - X. Zhang
    - Y. Xia
    - Z. Wang
    - A. K. Roy-Chowdhury
    - J. Li
  publisher: "submitted to IEEE Robotics and Automation Letters (RA-L), under review"
  # date: 2024-01-01
  image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2407.17460
    - type: paper_video
      text: Video
      link: https://www.youtube.com/watch?v=uXqPMaSyDek
    - type: paper_home
      text: Website
      link: https://sonic-social-nav.github.io/
    - type: paper_code
      text: Code
      link: https://github.com/tasl-lab/SoNIC/tree/main
  tags:
    - Uncertainty Quantification
    - Reinforcement Learning
    - Social Navigation

- title: "Multi-Agent Dynamic Relational Reasoning for Social Robot Navigation"
  authors:
    - 'J. Li\*'
    - 'C. Hua\*'
    - J. Park
    - H. Ma
    - V. Dax
    - M. J. Kochenderfer
  publisher: "submitted to IEEE Transactions on Robotics (T-RO), under review"
  # date: 2024-01-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2401.12275
  tags:
    - Trajectory Prediction
    - Relational Reasoning
    - Reinforcement Learning
    - Social Navigation

- title: "CMP: Cooperative Motion Prediction with Multi-Agent Communication"
  authors:
    - 'Z. Wu\*'
    - 'Y. Wang\*'
    - 'Z. Wang\*'
    - H. Ma
    - Z. Li
    - H. Qiu
    - J. Li
  publisher: "submitted to IEEE Robotics and Automation Letters (RA-L), under review"
  # date: 2024-01-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2403.17916
  tags:
    - Trajectory Prediction
    - Multi-agent System

- title: "Adaptive Prediction Ensemble: Improving Out-of-Distribution Generalization of Motion Forecasting"
  authors:
    - J. Li
    - J. Li
    - S. Bae
    - D. Isele
  publisher: "submitted to IEEE Robotics and Automation Letters (RA-L), under review"
  # date: 2024-01-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2407.09475
  tags:
    - Trajectory Prediction
    - Out-of-Distribution
    - Generalization


- title: "Self-supervised Multi-future Occupancy Forecasting for Autonomous Driving"
  authors:
    - J. Li
    - J. Li
    - S. Bae
    - D. Isele
  publisher: "submitted to IEEE Robotics and Automation Letters (RA-L), under review"
  # date: 2024-01-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2407.09475
  tags:
    - Trajectory Prediction
    - Out-of-Distribution
    - Generalization

- title: "Importance Sampling-Guided Meta-Training for Intelligent Agents in Highly Interactive Environments"
  authors:
    - "M. Arief*"
    - "M. Timmerman*"
    - J. Li
    - D. Isele
    - M. J. Kochenderfer
  publisher: "submitted to IEEE Robotics and Automation Letters (RA-L), under review"
  # date: 2024-01-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2407.09475
  tags:
    - Meta Learning
    - Autonomous Driving
    - Reinforcement learning

- title: "Integrating Graph and Recurrent Neural Networks for Spatiotemporal Reasoning"
  authors:
    - V. Dax
    - Z. Li
    - X. Zhang
    - H. Shekhar
    - J. Li
    - M. J. Kochenderfer
  publisher: "submitted to IEEE Transactions on Neural Networks and Learning Systems (T-NNLS)"
  # date: 2024-01-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: Arrive Soon
      # link: https://arxiv.org/abs/2407.09475
  tags:
    - Graph Neural Networks
    - Spatialtemporal Reasoning

- title: "The Generalization Gap of Locally Unordered GNNs"
  authors:
    - V. Dax
    - J. Li
    - M. J. Kochenderfer
  publisher: "under review"
  # date: 2024-01-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: Arrive Soon
      # link: https://arxiv.org/abs/2407.09475
  tags:
    - Graph Neural Networks

- title: "Interactive Autonomous Navigation with Internal State Inference and Interactivity Estimation"
  authors:
    - J. Li
    - D. Isele
    - K. Lee
    - J. Park
    - K. Fujimura
    - M. J. Kochenderfer
  publisher: "IEEE Transactions on Robotics (T-RO)"
  date: 2024-06-06
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2311.16091
  tags:
    - Autonomous Driving
    - Reinforcement Learning

- title: "Scene Informer: Anchor-based Occlusion Inference and Trajectory Prediction in Partially Observable Environments"
  authors:
    - B. Lange
    - J. Li
    - M. J. Kochenderfer
  publisher: "International Conference on Robotics and Automation (ICRA 2024)"
  date: 2024-03-09
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2309.13893
  tags:
    - Autonomous Driving
    - Trajectory Prediction
    - Occlusion Inference

- title: "MATRIX: Multi-Agent Trajectory Generation with Diverse Contexts"
  authors:
    - 'Z. Xu\*'
    - 'R. Zhou\*'
    - 'Y. Yin\*'
    - H. Gao
    - M. Tomizuka
    - J. Li
  publisher: "International Conference on Robotics and Automation (ICRA 2024)"
  date: 2024-03-09
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2403.06041
  tags:
    - Data Augmentation
    - Trajectory Generation


- title: "ELA: Exploited Level Augmentation for Offline Learning in Zero-Sum Games"
  authors:
    - 'S. Lei\*'
    - 'K. Lee\*'
    - L. Li
    - J. Park
    - J. Li
  publisher: "International Conference on Autonomous Agents and Multiagent Systems (AAMAS 2024)"
  date: 2024-02-28
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2402.18617
    - type: paper_link
      text: AAMAS
      link: https://www.ifaamas.org/Proceedings/aamas2024/pdfs/p2357.pdf
  tags:
    - Offline Learning
    - Zero-Sum Games

- title: "Rank2Tell: A Multimodal Dataset for Joint Driving Importance Ranking and Reasoning"
  authors:
    - 'E. Sachdeva\*'
    - 'N. Agarwal\*'
    - S. Chundi
    - S. Roelofs
    - J. Li
    - C. Choi
    - M. J. Kochenderfer
    - B. Dariush
  publisher: "IEEE/CVF Winter Conference on Applications of Computer Vision (WACV 2024)"
  date: 2024-02-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2309.06597
  tags:
    - Scene Understanding
    - Autonomous Driving

- title: "Predicting Future Spatiotemporal Occupancy Grids with Semantics for Autonomous Driving"
  authors:
    - M. Toyungyernsub
    - E. Yel
    - J. Li
    - M. J. Kochenderfer
  publisher: "IEEE Intelligent Vehicles Symposium (IV 2024)"
  date: 2024-01-01
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2310.01723
  tags:
    - Occupancy Prediction
    - Autonomous Driving

- title: "Pedestrian Crossing Action Recognition and Trajectory Prediction with 3D Human Keypoints"
  authors:
    - J. Li
    - 'X. Shi\*'
    - 'F. Chen\*'
    - 'J. Stroud\*'
    - Z. Zhang
    - T. Lan
    - J. Mao
    - J. Kang
    - K. Refaat
    - W. Yang
    - E. Le
    - C. Li
  publisher: "International Conference on Robotics and Automation (ICRA 2023)"
  date: 2023-07-30
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2306.01075
  tags:
    - Action Recognition
    - Autonomous Driving
    - Trajectory Prediction

- title: "Robust Driving Policy Learning with Guided Meta Reinforcement Learning"
  authors:
    - 'K. Lee\*'
    - 'J. Li\*'
    - D. Isele
    - J. Park
    - K. Fujimura
    - M. J. Kochenderfer
  publisher: "IEEE International Conference on Intelligent Transportation Systems (ITSC 2023)"
  date: 2023-07-19
  # image: ./paper_images/SoNIC.png
  buttons:
    - type: paper_link
      text: arXiv
      link: https://arxiv.org/abs/2307.10160
  tags:
    - Meta Learning
    - Autonomous Driving
    - Reinforcement Learning